In [ ]:
#huggingface'den data set çekildi
import pandas as pd
from datasets import load_dataset

# Login using e.g. `huggingface-cli login` to access this dataset
ds = load_dataset("navyakamath03/student_performance_train")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

student_performance_train.csv:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Generating train split:   0%|          | 0/8000774 [00:00<?, ? examples/s]

In [ ]:
#dataset dataframe olarak yüklendi
df = ds["train"].to_pandas()
df.head(5000)

,Age,Grade,Gender,Race,SES_Quartile,ParentalEducation,SchoolType,Locale,TestScore_Math,TestScore_Reading,...,GPA,AttendanceRate,StudyHours,InternetAccess,Extracurricular,PartTimeJob,ParentSupport,Romantic,FreeTime,GoOut
0,17,12,Female,White,3,HS,Public,Suburban,70.258235,79.665185,...,2.743879,0.906809,1.089243,1,1,0,0,0,2,2
1,18,12,Female,White,2,HS,Public,Suburban,67.876546,59.611505,...,2.587700,0.843739,0.879911,1,1,0,1,0,5,2
2,16,11,Female,White,2,HS,Public,City,62.070623,70.577443,...,2.426294,0.850923,1.003442,1,1,0,1,1,5,1
3,14,9,Female,White,4,Bachelors+,Public,Town,79.909312,82.924450,...,3.558240,0.946786,1.814810,1,1,0,1,0,4,2
4,16,11,Female,Two-or-more,4,SomeCollege,Public,Rural,90.562294,95.352336,...,3.896884,0.988036,1.157241,1,1,0,0,0,3,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,16,11,Female,Two-or-more,2,HS,Public,Suburban,72.644820,61.026809,...,3.002831,0.863079,0.256198,1,1,1,0,0,4,2
4996,18,12,Female,White,3,SomeCollege,Public,Suburban,76.934920,76.458110,...,2.898223,0.892053,0.792247,1,1,0,0,1,2,2
4997,16,11,Female,White,4,<HS,Public,Suburban,100.000000,82.732272,...,3.831692,0.950237,0.817939,1,1,0,0,0,3,2
4998,16,11,Female,Hispanic,2,Bachelors+,Public,City,66.984878,68.136544,...,2.864418,0.849447,0.727162,0,0,0,0,0,2,3
4999,14,9,Male,White,2,SomeCollege,Public,City,72.662444,85.197055,...,2.726654,0.919452,1.193954,1,0,1,1,0,4,3

In [ ]:
#kolonlardaki data tipleri incelendi.
df = ds["train"].to_pandas()
df.dtypes

Age                    int64
Grade                  int64
Gender                object
Race                  object
SES_Quartile           int64
ParentalEducation     object
SchoolType            object
Locale                object
TestScore_Math       float64
TestScore_Reading    float64
TestScore_Science    float64
GPA                  float64
AttendanceRate       float64
StudyHours           float64
InternetAccess         int64
Extracurricular        int64
PartTimeJob            int64
ParentSupport          int64
Romantic               int64
FreeTime               int64
GoOut                  int64
dtype: object

In [ ]:
#!mkdir navyakamath03
#df.to_csv("navyakamath03/student_performance_train.csv", index=True)
#BigQuery'ye aktarım için kütüphane yüklendi.
#from google.colab import auth
#auth.authenticate_user()
#BigQuery'ye aktarım yapılması için proje seçimi yapıldı.
#PROJECT_ID = "	project-193faa7c-f9be-4fea-b4d"
#!gcloud config set project $PROJECT_ID
#BigQuery'ye aktarım yapıldı.
#!gsutil cp navyakamath03/student_performance_train.csv gs://bitirme_projesi123/

In [ ]:
#BigQuery'deki temizlenmiş data colaba aktarıldı.

from google.colab import auth
auth.authenticate_user()
!gsutil -m cp gs://bq_export_mert/en_son_hali_*.csv .
import glob
import pandas as pd

output = "en_son_hali_final.csv"
first = True

files = glob.glob("en_son_hali_*.csv")
print("Bulunan dosya:", len(files))

for f in files:
    for chunk in pd.read_csv(f, chunksize=500_000):
        chunk.to_csv(output, mode="a", header=first, index=False)
        first = False

print("Hazır:", output)

Copying gs://bq_export_mert/en_son_hali_000000000000.csv...
Copying gs://bq_export_mert/en_son_hali_000000000001.csv...
Copying gs://bq_export_mert/en_son_hali_000000000002.csv...
Copying gs://bq_export_mert/en_son_hali_000000000003.csv...
Copying gs://bq_export_mert/en_son_hali_000000000004.csv...
Copying gs://bq_export_mert/en_son_hali_000000000006.csv...
Copying gs://bq_export_mert/en_son_hali_000000000009.csv...
Copying gs://bq_export_mert/en_son_hali_000000000008.csv...
Copying gs://bq_export_mert/en_son_hali_000000000005.csv...
Copying gs://bq_export_mert/en_son_hali_000000000007.csv...
Copying gs://bq_export_mert/en_son_hali_000000000010.csv...
Copying gs://bq_export_mert/en_son_hali_000000000011.csv...
Copying gs://bq_export_mert/en_son_hali_000000000012.csv...
Copying gs://bq_export_mert/en_son_hali_000000000013.csv...
Copying gs://bq_export_mert/en_son_hali_000000000014.csv...
Copying gs://bq_export_mert/en_son_hali_000000000015.csv...
Copying gs://bq_export_mert/en_son_hali_000000000016.csv...
Copying gs://bq_export_mert/en_son_hali_000000000017.csv...
Copying gs://bq_export_mert/en_son_hali_000000000018.csv...
Copying gs://bq_export_mert/en_son_hali_000000000019.csv...
Copying gs://bq_export_mert/en_son_hali_000000000020.csv...
Copying gs://bq_export_mert/en_son_hali_000000000021.csv...
Copying gs://bq_export_mert/en_son_hali_000000000022.csv...
Copying gs://bq_export_mert/en_son_hali_000000000023.csv...
Copying gs://bq_export_mert/en_son_hali_000000000025.csv...
Copying gs://bq_export_mert/en_son_hali_000000000024.csv...
Copying gs://bq_export_mert/en_son_hali_000000000026.csv...
Copying gs://bq_export_mert/en_son_hali_000000000027.csv...
Copying gs://bq_export_mert/en_son_hali_000000000028.csv...
Copying gs://bq_export_mert/en_son_hali_000000000029.csv...
Copying gs://bq_export_mert/en_son_hali_000000000030.csv...
Copying gs://bq_export_mert/en_son_hali_000000000031.csv...
Copying gs://bq_export_mert/en_son_hali_000000000032.csv...
Copying gs://bq_export_mert/en_son_hali_000000000033.csv...
Copying gs://bq_export_mert/en_son_hali_000000000034.csv...
Copying gs://bq_export_mert/en_son_hali_000000000036.csv...
Copying gs://bq_export_mert/en_son_hali_000000000035.csv...
Copying gs://bq_export_mert/en_son_hali_000000000037.csv...
Copying gs://bq_export_mert/en_son_hali_000000000038.csv...
Copying gs://bq_export_mert/en_son_hali_000000000039.csv...
Copying gs://bq_export_mert/en_son_hali_000000000040.csv...
Copying gs://bq_export_mert/en_son_hali_000000000041.csv...
Copying gs://bq_export_mert/en_son_hali_000000000042.csv...
Copying gs://bq_export_mert/en_son_hali_000000000043.csv...
Copying gs://bq_export_mert/en_son_hali_000000000044.csv...
Copying gs://bq_export_mert/en_son_hali_000000000045.csv...
Copying gs://bq_export_mert/en_son_hali_000000000046.csv...
Copying gs://bq_export_mert/en_son_hali_000000000047.csv...
Copying gs://bq_export_mert/en_son_hali_000000000048.csv...
Copying gs://bq_export_mert/en_son_hali_000000000049.csv...
\ [50/50 files][674.7 MiB/674.7 MiB] 100% Done  43.3 MiB/s ETA 00:00:00
Operation completed over 50 objects/674.7 MiB.
Bulunan dosya: 50
Hazır: en_son_hali_final.csv

In [ ]:
dff=pd.read_csv("en_son_hali_final.csv")
dff.head()

,Age,Grade,Gender,Race,SES_Quartile,ParentalEducation,SchoolType,Locale,InternetAccess,PartTimeJob,...,FreeTime,has_gf_bf,activity,sociability,TestScore_Math,TestScore_Reading,TestScore_Science,GPA,AttendanceRate,StudyHours
0,14,9,Male,White,3,Bachelors+,Private,Suburban,1,0,...,5,0,1,1,92.40,88.18,91.01,3.75,0.98,1.54
1,14,9,Male,Asian,4,SomeCollege,Public,Rural,1,0,...,2,0,1,1,75.73,71.05,70.88,2.80,0.88,1.35
2,14,9,Male,White,4,Bachelors+,Public,Suburban,1,0,...,4,0,0,1,68.44,78.16,69.28,1.89,0.90,1.23
3,14,9,Female,White,1,HS,Public,Rural,0,0,...,2,0,1,2,68.03,63.51,80.51,2.65,0.89,0.62
4,14,9,Female,Hispanic,1,<HS,Public,Rural,1,0,...,2,0,0,1,85.46,73.87,82.14,3.38,0.95,1.59

Başarı oranını etkileyen örüntülerin incelenmesi

In [ ]:
print(f"Minimum GPA: {dff['GPA'].min()}")
print(f"Maximum GPA: {dff['GPA'].max()}")
print(f"Min Attandance_Rate: {dff['AttendanceRate'].min()}")
print(f"Max Attandance_Rate: {dff['AttendanceRate'].max()}")
print(f"Min StudyHours: {dff['StudyHours'].min()}")
print(f"Max StudyHours: {dff['StudyHours'].max()}")

Minimum GPA: 0.71
Maximum GPA: 4.0
Min Attandance_Rate: 0.7
Max Attandance_Rate: 1.0
Min StudyHours: 0.0
Max StudyHours: 2.79

In [ ]:
import pandas as pd
import numpy as np

dff["attendance_class"] = np.where(
    dff["AttendanceRate"] >= 0.9, "High Attendance",
    np.where(dff["AttendanceRate"] >= 0.6, "Normal Attendance", "Low Attendance")
)
dff["Success_Rate"] = np.where(
    dff["GPA"] >= 3.0, "Successful",
    np.where(dff["GPA"] >= 2.0, "Regular", "Failed")
)
dff["Study_Rate"] = np.where(
    dff["StudyHours"] >= 2.0, "Hard Worker",
    np.where(dff["StudyHours"] >= 1.0, "Regular", "Lazy")
)

In [ ]:
dff["Success_Rate"].value_counts(normalize=True)

Success_Rate
Successful    0.504108
Regular       0.480222
Failed        0.015669
Name: proportion, dtype: float64

In [ ]:
features = [
    "attendance_class",
    "Study_Rate",
    "InternetAccess",
    "ParentSupport",
    "activity",
    "PartTimeJob",
    "has_gf_bf",
    "FreeTime",
    "sociability"
]

for col in features:
    print("\n", col)
    display(
        dff.groupby(col)["Success_Rate"]
          .value_counts(normalize=True)
          .unstack()
          .round(3)
    )

 attendance_class

Success_Rate       Failed  Regular  Successful
attendance_class
High Attendance     0.000    0.269       0.731
Normal Attendance   0.034    0.729       0.237

 Study_Rate

Success_Rate  Failed  Regular  Successful
Study_Rate
Hard Worker      NaN    0.097       0.903
Lazy           0.027    0.599       0.374
Regular        0.005    0.366       0.630

 InternetAccess

Success_Rate    Failed  Regular  Successful
InternetAccess
0                0.016    0.481       0.503
1                0.016    0.480       0.504

 ParentSupport

Success_Rate   Failed  Regular  Successful
ParentSupport
0               0.016     0.48       0.504
1               0.016     0.48       0.504

 activity

Success_Rate  Failed  Regular  Successful
activity
0              0.016     0.48       0.504
1              0.016     0.48       0.504

 PartTimeJob

Success_Rate  Failed  Regular  Successful
PartTimeJob
0              0.016    0.480       0.504
1              0.016    0.481       0.504

 has_gf_bf

Success_Rate  Failed  Regular  Successful
has_gf_bf
0              0.016     0.48       0.504
1              0.016     0.48       0.504

 FreeTime

Success_Rate  Failed  Regular  Successful
FreeTime
1              0.016    0.480       0.505
2              0.016    0.480       0.505
3              0.016    0.481       0.504
4              0.016    0.481       0.504
5              0.016    0.479       0.505

 sociability

Success_Rate  Failed  Regular  Successful
sociability
1              0.016    0.480       0.504
2              0.016    0.481       0.504
3              0.016    0.480       0.504
4              0.016    0.480       0.504
5              0.015    0.483       0.502

In [ ]:
pattern_2 = (
    dff.groupby(["attendance_class", "Study_Rate"])["Success_Rate"]
      .value_counts(normalize=True)
      .unstack()
      .round(3)
      .reset_index()
)

pattern_2

Success_Rate   attendance_class   Study_Rate  Failed  Regular  Successful
0               High Attendance  Hard Worker     NaN    0.079       0.921
1               High Attendance         Lazy   0.001    0.348       0.652
2               High Attendance      Regular   0.000    0.227       0.773
3             Normal Attendance  Hard Worker     NaN    0.509       0.491
4             Normal Attendance         Lazy   0.044    0.755       0.201
5             Normal Attendance      Regular   0.014    0.677       0.309

25-75 denemesi

In [ ]:
dff["Success_Rate_global"] = pd.qcut(
    dff["GPA"],
    q=[0, 0.25, 0.75, 1],
    labels=["Failed", "Regular", "Successfull"])

In [ ]:
dff["Success_Rate_global"].value_counts(normalize=True)

Success_Rate_global
Regular        0.493559
Failed         0.256822
Successfull    0.249619
Name: proportion, dtype: float64

In [ ]:
dff.groupby("Success_Rate_global")["GPA"].agg(
    min_gpa="min",
    max_gpa="max",
    count="count")

/tmp/ipython-input-1314316105.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dff.groupby("Success_Rate_global")["GPA"].agg(

                     min_gpa  max_gpa    count
Success_Rate_global
Failed                  0.71     2.69  2054776
Regular                 2.70     3.31  3948854
Successfull             3.32     4.00  1997144

In [ ]:
dff.groupby(
    "Success_Rate_global",
    observed=False
).agg(

    median_study=("StudyHours", "median"),
    median_att=("AttendanceRate", "median"),

)

                     median_study  median_att
Success_Rate_global
Failed                       0.83        0.86
Regular                      1.00        0.90
Successfull                  1.17        0.94

In [ ]:
dff["attendance_class"] = np.where(
    dff["AttendanceRate"] >= 0.94, "High Attendance",
    np.where(dff["AttendanceRate"] >= 0.9, "Normal Attendance", "Low Attendance")
)
dff["Study_Rate"] = np.where(
    dff["StudyHours"] >= 1.17, "Hard Worker",
    np.where(dff["StudyHours"] >= 1.0, "Regular", "Lazy")
)

In [ ]:
features = [
    "attendance_class",
    "Study_Rate",
    "InternetAccess",
    "ParentSupport",
    "activity",
    "PartTimeJob",
    "has_gf_bf",
    "FreeTime",
    "sociability"
]

for col in features:
    print("\n", col)
    display(
        dff.groupby(col)["Success_Rate_global"]
          .value_counts(normalize=True)
          .unstack()
          .round(3)
    )

 attendance_class

Success_Rate_global  Failed  Regular  Successfull
attendance_class
High Attendance       0.022    0.368        0.611
Low Attendance        0.468    0.476        0.056
Normal Attendance     0.121    0.619        0.260

 Study_Rate

Success_Rate_global  Failed  Regular  Successfull
Study_Rate
Hard Worker           0.123    0.477        0.400
Lazy                  0.361    0.491        0.148
Regular               0.210    0.527        0.263

 InternetAccess

Success_Rate_global  Failed  Regular  Successfull
InternetAccess
0                     0.258    0.493        0.249
1                     0.257    0.494        0.250

 ParentSupport

Success_Rate_global  Failed  Regular  Successfull
ParentSupport
0                     0.257    0.494        0.249
1                     0.257    0.493        0.250

 activity

Success_Rate_global  Failed  Regular  Successfull
activity
0                     0.257    0.494        0.249
1                     0.257    0.493        0.250

 PartTimeJob

Success_Rate_global  Failed  Regular  Successfull
PartTimeJob
0                     0.257    0.493        0.250
1                     0.257    0.494        0.249

 has_gf_bf

Success_Rate_global  Failed  Regular  Successfull
has_gf_bf
0                     0.257    0.494         0.25
1                     0.257    0.494         0.25

 FreeTime

Success_Rate_global  Failed  Regular  Successfull
FreeTime
1                     0.256    0.494        0.250
2                     0.257    0.493        0.250
3                     0.257    0.494        0.250
4                     0.257    0.494        0.249
5                     0.256    0.494        0.250

 sociability

Success_Rate_global  Failed  Regular  Successfull
sociability
1                     0.257    0.494        0.250
2                     0.257    0.493        0.250
3                     0.257    0.494        0.249
4                     0.257    0.494        0.249
5                     0.258    0.491        0.251

**AttandanceRate’i etkileyen faktörlerin incelenmesi**

In [ ]:
# AttendanceRate ile Sayısal Değişkenlerin Korelasyon Analizi
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Sadece sayısal (float ve int) olan sütunları analiz için seçiyoruz
numeric_cols = dff.select_dtypes(include=['float64', 'int64'])

# AttendanceRate sütununun diğer değişkenlerle olan korelasyonunu hesaplıyoruz
attendance_corr = numeric_cols.corr()['AttendanceRate'].sort_values(ascending=False)

print("AttendanceRate ile En Çok İlişkili Faktörler (Korelasyon):")
print(attendance_corr)

# Görselleştirme: Korelasyon Isı Haritası (Heatmap)
plt.figure(figsize=(4, 10))
sns.heatmap(numeric_cols.corr()[['AttendanceRate']].sort_values(by='AttendanceRate', ascending=False),
            annot=True,
            cmap='RdYlGn', # Kırmızıdan Yeşile (Pozitif-Negatif ayrımı için)
            fmt=".2f")
plt.title('AttendanceRate ile Değişkenlerin İlişkisi')
plt.show()

In [ ]:
# Kategorik Değişkenlerin AttendanceRate Üzerindeki Etkisini İnceleme
import matplotlib.pyplot as plt
import seaborn as sns

# Okul Türü (SchoolType) ve Bölge (Locale) Bazlı Katılım Ortalamaları
plt.figure(figsize=(14, 5))

# Sol Grafik: Okul Türü
plt.subplot(1, 2, 1)
sns.barplot(data=dff, x='SchoolType', y='AttendanceRate', palette='Blues_d')
plt.title('Okul Türüne Göre Katılım Oranı')
plt.ylim(0.8, 1.0) # Farkları daha net görmek için

# Sağ Grafik: Bölge (Locale)
plt.subplot(1, 2, 2)
sns.barplot(data=dff, x='Locale', y='AttendanceRate', palette='Greens_d')
plt.title('Yaşanılan Bölgeye Göre Katılım Oranı')
plt.ylim(0.8, 1.0)

plt.tight_layout()
plt.show()

# Sayısal Olarak Grupları Görme
print("--- Okul Türü Bazında Katılım ---")
print(dff.groupby('SchoolType')['AttendanceRate'].mean())

print("\n--- Bölge (Locale) Bazında Katılım ---")
print(dff.groupby('Locale')['AttendanceRate'].mean())

In [ ]:
# Kişisel Faktörlerin AttendanceRate Üzerindeki Etkisi
import matplotlib.pyplot as plt
import seaborn as sns

# Kişisel faktörlerin listesi
lifestyle_factors = ['PartTimeJob', 'has_gf_bf', 'ParentSupport']

plt.figure(figsize=(18, 5))

for i, factor in enumerate(lifestyle_factors):
    plt.subplot(1, 3, i+1)
    sns.barplot(data=dff, x=factor, y='AttendanceRate', hue=factor, palette='Set2', legend=False)
    plt.title(f'{factor} vs Katılım Oranı')
    plt.ylim(0.8, 1.0)

plt.tight_layout()
plt.show()

# Sayısal ortalamaları kontrol edelim
for factor in lifestyle_factors:
    print(f"--- {factor} Bazında Katılım ---")
    print(dff.groupby(factor)['AttendanceRate'].mean())
    print("-" * 30)

In [ ]:
# Risk Altındaki Öğrencilerin (%10 En Düşük Katılım) Analizi

# Eşik değerini belirliyoruz (En düşük %10'luk dilim)
threshold = dff['AttendanceRate'].quantile(0.10)
dff['At_Risk'] = dff['AttendanceRate'] <= threshold

print(f"Katılım Oranı Eşik Değeri (En Düşük %10): {threshold:.2f}")

# Riskli Grup ile Normal Grubu Kıyaslayalım
risk_profile = dff.groupby('At_Risk')[['GPA', 'StudyHours', 'TestScore_Math', 'SES_Quartile']].mean()

print("\n--- Riskli Grup vs. Diğerleri (Ortalama Farklar) ---")
print(risk_profile)

# Görselleştirme: Riskli Grupta Aile Geliri Dağılımı
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 5))
sns.countplot(data=dff[dff['At_Risk'] == True], x='SES_Quartile', palette='OrRd')
plt.title('Risk Altındaki Öğrencilerin (Düşük Katılım) Aile Gelir Dağılımı')
plt.xlabel('Aile Gelir Seviyesi (1: En Düşük, 4: En Yüksek)')
plt.ylabel('Öğrenci Sayısı')
plt.show()

In [ ]:
# Sosyal Faktörlerin Riskli Gruptaki Etkisi
import matplotlib.pyplot as plt
import seaborn as sns

# Riskli ve Normal grupların sosyal hayatlarını kıyaslayalım
social_comparison = dff.groupby('At_Risk')[['FreeTime', 'sociability', 'activity']].mean()

print("--- Riskli Grup vs. Diğerleri (Sosyal Hayat Faktörleri) ---")
print(social_comparison)

# Görselleştirme: Boş Zaman ve Sosyalleşme Karşılaştırması
plt.figure(figsize=(12, 6))

# Boş Zaman Dağılımı
plt.subplot(1, 2, 1)
sns.boxplot(data=dff, x='At_Risk', y='FreeTime', hue='At_Risk', palette='cool', legend=False)
plt.title('Risk Durumuna Göre Boş Zaman (FreeTime)')

# Sosyalleşme Oranı
plt.subplot(1, 2, 2)
sns.boxplot(data=dff, x='At_Risk', y='sociability', hue='At_Risk', palette='summer', legend=False)
plt.title('Risk Durumuna Göre Sosyalleşme (Sociability)')

plt.tight_layout()
plt.show()

In [ ]:
# Gruplara Göre Risk Altında Olma Olasılığı (%)

def risk_percentage(column_name):
    return dff.groupby(column_name)['At_Risk'].mean() * 100

# Analiz etmek istediğimiz orijinal sütun isimleri
factors_to_check = ['SES_Quartile', 'ParentSupport', 'InternetAccess', 'PartTimeJob']

print("--- Grupların Riskli Bölgeye (En Düşük %10 Katılım) Girme Olasılıkları (%) ---")
for factor in factors_to_check:
    print(f"\n{factor} Bazında Risk Oranı:")
    print(risk_percentage(factor))

# Görselleştirme: Aile Desteği ve Gelir Durumunun Risk Oranına Etkisi
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 5))

# Aile Desteği vs Risk Oranı
plt.subplot(1, 2, 1)
risk_data = dff.groupby('ParentSupport')['At_Risk'].mean().reset_index()
risk_data['At_Risk'] *= 100 # Yüzdeye çevir
sns.barplot(data=risk_data, x='ParentSupport', y='At_Risk', hue='ParentSupport', palette='Reds_r', legend=False)
plt.title('Aile Desteği Yoksa Risk % Kaç Artıyor?')
plt.ylabel('Risk Altındaki Öğrenci Oranı (%)')

# Gelir Durumu (SES_Quartile) vs Risk Oranı
plt.subplot(1, 2, 2)
income_risk = dff.groupby('SES_Quartile')['At_Risk'].mean().reset_index()
income_risk['At_Risk'] *= 100
sns.barplot(data=income_risk, x='SES_Quartile', y='At_Risk', hue='SES_Quartile', palette='YlOrRd', legend=False)
plt.title('Gelir Seviyesine Göre Risk Oranı (%)')
plt.ylabel('Risk Altındaki Öğrenci Oranı (%)')

plt.tight_layout()
plt.show()

In [ ]:
# Kesişimsel Risk Analizi
# Olumsuz faktörlerin birleştiği "Hassas Grupları" oluşturalım

# Senaryo 1: Düşük Gelir (SES=1) VE Aile Desteği Yok (0)
dff['LowSES_NoSupport'] = (dff['SES_Quartile'] == 1) & (dff['ParentSupport'] == 0)

# Senaryo 2: Düşük Gelir (SES=1) VE İnternet Yok (0)
dff['LowSES_NoInternet'] = (dff['SES_Quartile'] == 1) & (dff['InternetAccess'] == 0)

print("--- Hassas Grupların Risk Oranları (%) ---")

print("\nDüşük Gelir + Aile Desteği Yok Grubu:")
print(dff.groupby('LowSES_NoSupport')['At_Risk'].mean() * 100)

print("\nDüşük Gelir + İnternet Yok Grubu:")
print(dff.groupby('LowSES_NoInternet')['At_Risk'].mean() * 100)

# Görselleştirme: Kesişimsel Riskler
import matplotlib.pyplot as plt
import seaborn as sns

groups = ['LowSES_NoSupport', 'LowSES_NoInternet']
risk_values = [dff[dff[g] == True]['At_Risk'].mean() * 100 for g in groups]
normal_risk = dff['At_Risk'].mean() * 100

plt.figure(figsize=(10, 6))
sns.barplot(x=groups + ['Genel Ortalama'], y=risk_values + [normal_risk], palette='coolwarm')
plt.axhline(normal_risk, color='black', linestyle='--')
plt.title('Birden Fazla Olumsuz Faktör Birleştiğinde Risk Değişiyor mu?')
plt.ylabel('Risk Altındaki Öğrenci Oranı (%)')
plt.show()

In [ ]:
# Çalışma Alışkanlıkları (StudyHours) ve Katılım Arasındaki İlişki

# 1. Çalışma saatlerini gruplara ayıralım (Örn: 0-1 saat, 1-2 saat, 2+ saat)
def study_group(hours):
    if hours < 1: return 'Düşük (0-1 sa)'
    elif hours < 2: return 'Orta (1-2 sa)'
    else: return 'Yüksek (2+ sa)'

dff['Study_Group'] = dff['StudyHours'].apply(study_group)

# 2. Çalışma gruplarına göre Risk Oranı (%) ve Ortalama Katılım
study_analysis = dff.groupby('Study_Group').agg({
    'AttendanceRate': 'mean',
    'At_Risk': 'mean'
}).reset_index()

study_analysis['At_Risk'] *= 100 # Yüzdeye çevir
print("--- Çalışma Saatlerine Göre Katılım ve Risk Analizi ---")
print(study_analysis)

# 3. Görselleştirme
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.barplot(data=study_analysis, x='Study_Group', y='At_Risk', hue='Study_Group', palette='plasma', legend=False)
plt.title('Çalışma Alışkanlığı Azaldıkça Devamsızlık Riski Artıyor mu?')
plt.ylabel('Risk Altındaki Öğrenci Oranı (%)')
plt.show()

In [ ]:
# Sosyal Hayat Düzeylerinin (sociability ve FreeTime) Katılım Riskiyle İlişkisi

# 1. Sosyalleşme (sociability) düzeyini gruplara ayıralım (1-2: Düşük, 3: Orta, 4-5: Yüksek)
def social_level(val):
    if val <= 2: return 'Düşük (1-2)'
    elif val == 3: return 'Orta (3)'
    else: return 'Yüksek (4-5)'

dff['Social_Level'] = dff['sociability'].apply(social_level)
dff['FreeTime_Level'] = dff['FreeTime'].apply(social_level) # Aynı mantığı FreeTime için de kullanalım

# 2. Sosyal düzeylere göre Risk Oranı (%) analizi
social_risk = dff.groupby('Social_Level')['At_Risk'].mean() * 100
freetime_risk = dff.groupby('FreeTime_Level')['At_Risk'].mean() * 100

print("--- Sosyalleşme Düzeyine Göre Devamsızlık Riski (%) ---")
print(social_risk)
print("\n--- Boş Zaman Düzeyine Göre Devamsızlık Riski (%) ---")
print(freetime_risk)

# 3. Görselleştirme: Sosyal Hayat vs Risk
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
sns.barplot(x=social_risk.index, y=social_risk.values, hue=social_risk.index, palette='coolwarm', legend=False)
plt.title('Dışarı Çıkma Sıklığı Risk Oranını Değiştiriyor mu?')
plt.ylabel('Risk Altındaki Öğrenci Oranı (%)')

plt.subplot(1, 2, 2)
sns.barplot(x=freetime_risk.index, y=freetime_risk.values, hue=freetime_risk.index, palette='viridis', legend=False)
plt.title('Boş Vakit Miktarı Risk Oranını Değiştiriyor mu?')
plt.ylabel('Risk Altındaki Öğrenci Oranı (%)')

plt.show()

In [ ]:
# Ebeveyn Eğitim Seviyesi (ParentalEducation) ve Katılım Riski

# 1. Eğitim seviyelerine göre Risk Oranı (%) ve Ortalama Katılım
parent_edu_analysis = dff.groupby('ParentalEducation').agg({
    'AttendanceRate': 'mean',
    'At_Risk': 'mean'
}).sort_values(by='At_Risk', ascending=False).reset_index()

parent_edu_analysis['At_Risk'] *= 100

print("--- Ebeveyn Eğitim Seviyesine Göre Katılım Analizi ---")
print(parent_edu_analysis)

# 2. Görselleştirme
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 6))
sns.barplot(data=parent_edu_analysis, x='ParentalEducation', y='At_Risk', hue='ParentalEducation', palette='magma', legend=False)
plt.title('Ebeveyn Eğitim Seviyesi Devamsızlık Riskini Etkiliyor mu?')
plt.ylabel('Risk Altındaki Öğrenci Oranı (%)')
plt.xticks(rotation=45)
plt.show()

In [ ]:
# Katılım Oranı (AttendanceRate) vs. Akademik Başarı

# 1. Katılım oranlarını mantıklı gruplara ayıralım
def attendance_bucket(rate):
    if rate < 0.85: return '1. Düşük (<%85)'
    elif rate < 0.95: return '2. Orta (%85-95)'
    else: return '3. Yüksek (>%95)'

dff['Attendance_Level'] = dff['AttendanceRate'].apply(attendance_bucket)

# 2. Katılım seviyelerine göre tüm başarı metriklerinin ortalamasını alalım
score_analysis = dff.groupby('Attendance_Level').agg({
    'GPA': 'mean',
    'TestScore_Math': 'mean',
    'TestScore_Reading': 'mean',
    'TestScore_Science': 'mean'
}).reset_index()

print("--- Katılım Seviyesine Göre Başarı Tablosu ---")
print(score_analysis)

# 3. Görselleştirme: Katılım Seviyesi vs Notlar
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 6))
# Notları "melt" ederek tek bir grafikte gösterelim
melted_scores = score_analysis.melt(id_vars='Attendance_Level', var_name='Ders', value_name='Ortalama_Not')
sns.barplot(data=melted_scores, x='Attendance_Level', y='Ortalama_Not', hue='Ders', palette='muted')

plt.title('Okula Katılım Arttıkça Başarı Nasıl Değişiyor?', fontsize=15)
plt.ylabel('Ortalama Puan / Not')
plt.ylim(0, 100) # Skorlar 100 üzerinden olduğu için
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

Study_Rate'i etkileyen faktörlerin incelenmesi:

*“Öğrencilerin çalışma düzenini (Study_Rate) hangi faktörler etkiliyor ve bu durum başarıya nasıl yansıyor?”

-Study_Rate, öğrencinin öğrenmeye ayırdığı gerçek eforu temsil eder.

-Study_Rate'i etkileyecek faktörleri sıralarsak;
*Study_Rate vs Sociability
*Study_Rate vs FreeTime
*Study_Rate vs ParentSupport
*Study_Rate vs InternetAccess
*Study_Rate vs Attendance
*Study_Rate vs Grade olabilir. Şimdi bunların analizlerini inceleyelim.

In [ ]:
dff.groupby("Study_Rate")["sociability"].mean()

#Sosyal aktivitenin Study_Rate'e etkisi pek olmuyor.

In [ ]:
dff.groupby("Study_Rate")["FreeTime"].mean()
#Fazla boş zaman düşük yapılandırılmış çalışmaya sebep olabiliyor.

In [ ]:
dff.groupby("Study_Rate")["ParentSupport"].mean()
#Aile desteği yüksek öğrenciler daha düzenli çalışıyor.

In [ ]:
dff.groupby("Study_Rate")["InternetAccess"].mean()
#İnternet erişimi öğrenme fırsatlarını artırıyor.

In [ ]:
dff.groupby("Study_Rate")["AttendanceRate"].mean()
#Devamlılık, çalışma disiplininin öncül göstergelerinden birisidir.

In [ ]:
dff.groupby("Study_Rate")["Grade"].mean()
#Üst sınıflarda çalışma yükü artıyor.